### ISSUE TITLE
Recursion and Dynamic Programming 

### ISSUE THREAD

**Issue by Sgt-Forge** [Sgt-Forge/Interview-Studying#1]
# Summary
My additions to the chapter for "1. Recursion and Dynamic Programming"

# ToDo
- [ ] Define recursion
- [ ] Define Dynamic Programming
    - [ ] Define Bottom-Up / Tabulation / Dynamic Programming
    - [ ] Define Top-Down / Memoization 
- [ ] Define Half-and-Half
- Examples:
    - [ ] Fibonacci numbers
